### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by moritzhoferer** [nathancunn/pushshiftR#1]
I am running R 3.6.2 on Ubuntu 18.4.4 LTS and tried to install pushshiftR, but with out success. I tried it directly from GitHub with `devtools::install_github("https://github.com/nathancunn/pushshiftR")` and get the following output:
```
Downloading GitHub repo nathancunn/pushshiftR@master
✓  checking for file ‘/tmp/RtmpwS5R5b/remotes70642383ff8e/nathancunn-pushshiftR-080f76d/DESCRIPTION’ ...
─  preparing ‘pushshiftR’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘pushshiftR_0.0.0.9000.tar.gz’
   
Installing package into ‘/home/mhoferer/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package ‘pushshiftR’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
Error : (converted from warning) /tmp/RtmpLICJD5/R.INSTALL7844bccdb3b/pushshiftR/man/grapes-not-in-grapes.Rd: \name should not contain !, | or @
ERROR: installing Rd objects failed for package ‘pushshiftR’
* removing ‘/home/mhoferer/R/x86_64-pc-linux-gnu-library/3.6/pushshiftR’
installation of package ‘/tmp/RtmpwS5R5b/file70643e476c1c/pushshiftR_0.0.0.9000.tar.gz’ had non-zero exit status
```
Could you help me with this? Thanks for your efforts!

Best,
Moritz

**Comment by nathancunn** [comment]
Hey @moritzhoferer,

Numerous months later, I know, so probably irrelevant by now. I had my notifications for this turned off 🙄 

The issue was caused by a function name containing "!", which is fine for Windows apparently, but not Linux. This has been adressed now and works on my end.

**Comment by moritzhoferer** [comment]
Hi @nathancunn 

Thanks for taking care. In the meantime I found another solution, but it will come in handy later. Now the installation also works for me.

Thanks for your effort!
